# Generated by Django 3.1 on 2020-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='directors_preview'),
        ),
    ]
