# Generated by Django 3.1 on 2020-09-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0002_show_showphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showphoto',
            name='show',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
