# Generated by Django 3.1 on 2020-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0002_auto_20200903_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=30)),
                ('video', models.FileField(blank=True, null=True, upload_to='preview_video')),
            ],
        ),
        migrations.RenameModel(
            old_name='About',
            new_name='About_U',
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='Addres',
        ),
    ]
