# Generated by Django 3.1 on 2020-09-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0005_auto_20200904_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showphoto',
            name='show',
        ),
        migrations.RemoveField(
            model_name='album',
            name='number',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='isTitleImg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='number',
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ometa.album'),
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
