# Generated by Django 3.1 on 2020-09-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0006_auto_20200904_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='photograph',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photograph', to='ometa.photographer'),
        ),
    ]
