# Generated by Django 3.1 on 2020-09-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0009_auto_20200904_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='isTitle',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
