# Generated by Django 3.1 on 2020-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0010_auto_20200904_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photo/'),
        ),
    ]
