# Generated by Django 3.1 on 2020-09-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0011_auto_20200904_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='director',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='work',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
