# Generated by Django 3.1 on 2020-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0012_auto_20200907_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview_video',
            name='isTitle',
        ),
        migrations.AddField(
            model_name='preview_video',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
