# Generated by Django 3.1 on 2020-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ometa', '0013_auto_20201219_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview_video',
            name='nameSecond',
            field=models.CharField(default='No name', max_length=30),
        ),
    ]
